### ISSUE TITLE
Default values seems not working

### ISSUE THREAD

**Issue by didix16** [graphology/graphology-canvas#4]
Hi guys. I'm just trying to render a graph but It throws to me some errors:

When I try to do this:
renderToPNG(graph, './graph.png', () => console.log('Done!'));

I get that error

/root/node_modules/graphology-canvas/defaults.js:27
    throw new Error('graphology-canvas: need at least a valid width or height!');
    ^

Error: graphology-canvas: need at least a valid width or height!
    at refineSettings (/root/node_modules/graphology-canvas/defaults.js:27:11)
    at renderToPNG (/root/node_modules/graphology-canvas/node.js:18:14)
    at Object.<anonymous> (/root/app.js:93:1)

And if I pass the values it asking then:

renderToPNG(graph, './graph.png', {width: 2048, height: 2048}, () => console.log('Done!'));

Error: graphology-canvas: the "r1" node has no valid x or y position. Expecting a number.
    at Object.exports.DEFAULT_NODE_REDUCER (/root/node_modules/graphology-canvas/defaults.js:52:11)
    at /root/node_modules/graphology-canvas/helpers.js:33:21
    at /root/node_modules/graphology/dist/graphology.cjs.js:4456:7
    at Map.forEach (<anonymous>)
    at Graph.forEachNode (/root/node_modules/graphology/dist/graphology.cjs.js:4455:17)
    at Object.reduceNodes (/root/node_modules/graphology-canvas/helpers.js:27:9)
    at Object.renderSync (/root/node_modules/graphology-canvas/renderer.js:23:26)
    at Object.render (/root/node_modules/graphology-canvas/index.js:18:7)
    at renderToPNG (/root/node_modules/graphology-canvas/node.js:24:7)
    at Object.<anonymous> (/root/app.js:93:1)

In documentation does not mention we have to pass some positional values ( I expected that library positioned nodes by its own) . Also tells that width and height are optional but as you can see actually they are not.

Hope you can help me.

Thanks

**Comment by Yomguithereal** [comment]
Hello @didix16,

Regarding your first problem I must have messed up something. Let me fix this.

Regarding the second problem, yes you must provide positions for your node using some layout such as [ForceAtlas2](https://github.com/graphology/graphology-layout-forceatlas2) to do so. I will add this to the doc and throw a more meaningful error.

**Comment by Yomguithereal** [comment]
@didix16 v0.3.1 is now published on npm. It should fix your issue. Note that if you need something more "battery-included" and less low-level, [net-to-img](https://github.com/jacomyal/net-to-img) might be a good fit for you as it packages all this in a more convenient way if you don't need to tweak things very precisely.

**Comment by didix16** [comment]
Thanks @Yomguithereal for answering so fast. Perfect, I'm gonna try then net-to-img and see if fits to me.

Thank you for your effort!
